const Performatives = {
    FAULT_REPAIRED_AND_RELEASED_FUND: "FAULT REPAIRED AND RELEASED FUND",
    NEGOTIATION:"NEGOTIATION",
    ACCEPT:"ACCEPT",
    REQUEST_OFFER:"REQUEST_OFFER",
    FAULT_AGENT:"FAULT AGENT",
    SERVICE_AGENT:"SERVICE AGENT",
    HANDSHAKE:"HANDSHAKE"
  };
  
  export default Performatives;
  